---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: Remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_distribution in ["Ubuntu", "Debian"]
  
  - name: Remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: update repository index for CentOS distr
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Remove apache2 package for CentOS distr
    dnf:
      name: httpd
      state: absent
    when: ansible_distribution == "CentOS"
  
  - name: Remove php support for apache for CentOS distr 
    dnf:
      name: php
      state: absent
    when: ansible_distribution == "CentOS"

